name: jhp_github_repo_finder
description: "GitHub Repository search and bookmark app by JHP"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # HTTP 통신
  http: ^1.1.0

  # 로컬 데이터베이스
  hive: ^2.2.3
  hive_flutter: ^1.1.0

  # 라우팅
  go_router: ^12.1.1

  # 상태 관리
  provider: ^6.1.1

  # JSON 어노테이션
  json_annotation: ^4.8.1

  # 기타 유틸리티
  cached_network_image: ^3.3.0

  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

  # Hive 코드 생성
  hive_generator: ^2.0.1
  build_runner: ^2.4.7

flutter:

  uses-material-design: true